# Generated by Django 4.2.15 on 2026-06-29 02:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LLMProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("deepseek", "DeepSeek"),
                            ("qwen", "Tongyi Qianwen"),
                            ("openai", "OpenAI"),
                            ("custom", "Custom OpenAI Compatible"),
                            ("debug", "Debug"),
                        ],
                        default="custom",
                        max_length=30,
                    ),
                ),
                ("base_url", models.URLField(blank=True, max_length=500)),
                ("api_key", models.CharField(blank=True, max_length=500)),
                ("model", models.CharField(max_length=100)),
                ("timeout", models.PositiveIntegerField(default=60)),
                ("is_active", models.BooleanField(default=False)),
                ("is_enabled", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "llm_providers",
                "ordering": ["-is_active", "name"],
            },
        ),
    ]
