# Generated by Django 4.2.15 on 2026-06-23 09:20

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        pgvector.django.VectorExtension(),
        migrations.CreateModel(
            name='ParagraphEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=200)),
                ('dimensions', models.PositiveIntegerField()),
                ('vector', pgvector.django.VectorField()),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('paragraph', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='document.paragraph')),
            ],
            options={
                'db_table': 'paragraph_embeddings',
                'ordering': ['-updated_at'],
            },
        ),
    ]
