# Generated by Django 4.2.15 on 2025-07-17 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeBase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="知识库名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="图标"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "活跃"),
                            ("inactive", "非活跃"),
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("is_public", models.BooleanField(default=False, verbose_name="是否公开")),
                ("chunk_size", models.IntegerField(default=1000, verbose_name="分块大小")),
                (
                    "chunk_overlap",
                    models.IntegerField(default=200, verbose_name="分块重叠"),
                ),
                (
                    "similarity_threshold",
                    models.FloatField(default=0.7, verbose_name="相似度阈值"),
                ),
                ("top_k", models.IntegerField(default=5, verbose_name="返回数量")),
                (
                    "documents_count",
                    models.IntegerField(default=0, verbose_name="文档数量"),
                ),
                ("chunks_count", models.IntegerField(default=0, verbose_name="分块数量")),
                (
                    "total_size",
                    models.BigIntegerField(default=0, verbose_name="总大小(字节)"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识库",
                "verbose_name_plural": "知识库",
                "db_table": "knowledge_bases",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeBaseSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("auto_index", models.BooleanField(default=True, verbose_name="自动索引")),
                (
                    "index_schedule",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="索引计划"
                    ),
                ),
                (
                    "search_mode",
                    models.CharField(
                        choices=[
                            ("semantic", "语义检索"),
                            ("keyword", "关键词检索"),
                            ("hybrid", "混合检索"),
                        ],
                        default="semantic",
                        max_length=20,
                        verbose_name="检索模式",
                    ),
                ),
                (
                    "enable_rerank",
                    models.BooleanField(default=False, verbose_name="启用重排序"),
                ),
                (
                    "rerank_model",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="重排序模型"
                    ),
                ),
                (
                    "knowledge_base",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="knowledge_base.knowledgebase",
                        verbose_name="知识库",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识库设置",
                "verbose_name_plural": "知识库设置",
                "db_table": "knowledge_base_settings",
            },
        ),
        migrations.CreateModel(
            name="KnowledgeBaseTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="标签名称")),
                (
                    "color",
                    models.CharField(
                        default="#1890ff", max_length=20, verbose_name="标签颜色"
                    ),
                ),
                (
                    "knowledge_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="knowledge_base.knowledgebase",
                        verbose_name="知识库",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识库标签",
                "verbose_name_plural": "知识库标签",
                "db_table": "knowledge_base_tags",
                "unique_together": {("knowledge_base", "name")},
            },
        ),
        migrations.CreateModel(
            name="KnowledgeBaseShare",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("permissions", models.JSONField(default=dict, verbose_name="权限")),
                (
                    "permission",
                    models.CharField(
                        choices=[("read", "只读"), ("write", "读写"), ("admin", "管理")],
                        default="read",
                        max_length=20,
                        verbose_name="权限级别",
                    ),
                ),
                (
                    "knowledge_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="knowledge_base.knowledgebase",
                        verbose_name="知识库",
                    ),
                ),
                (
                    "shared_with",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_knowledge_bases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="分享给",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识库分享",
                "verbose_name_plural": "知识库分享",
                "db_table": "knowledge_base_shares",
                "unique_together": {("knowledge_base", "shared_with")},
            },
        ),
    ]
