# Generated by Django 4.2.15 on 2026-06-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgebaseshare",
            name="permission",
            field=models.CharField(
                choices=[("read", "只读"), ("write", "读写")],
                default="read",
                max_length=20,
                verbose_name="权限级别",
            ),
        ),
    ]
