# Generated by Django 4.2.15 on 2025-07-17 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("knowledge_base", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="文档名称")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("base", "通用类型"),
                            ("web", "Web站点"),
                            ("qa", "问答对"),
                            ("table", "表格"),
                            ("markdown", "Markdown"),
                            ("text", "纯文本"),
                        ],
                        default="base",
                        max_length=20,
                        verbose_name="文档类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "处理失败"),
                            ("embedding", "向量化中"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="文档状态",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="文件路径"
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, verbose_name="文件大小(字节)"),
                ),
                ("char_length", models.IntegerField(default=0, verbose_name="字符数")),
                ("paragraph_count", models.IntegerField(default=0, verbose_name="段落数")),
                (
                    "hit_handling_method",
                    models.CharField(
                        choices=[("optimization", "优化"), ("directly_return", "直接返回")],
                        default="optimization",
                        max_length=20,
                        verbose_name="命中处理方式",
                    ),
                ),
                (
                    "directly_return_similarity",
                    models.FloatField(default=0.9, verbose_name="直接返回相似度阈值"),
                ),
                ("meta", models.JSONField(default=dict, verbose_name="元数据")),
                ("hit_count", models.IntegerField(default=0, verbose_name="命中次数")),
                (
                    "last_hit_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后命中时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "knowledge_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="knowledge_base.knowledgebase",
                        verbose_name="知识库",
                    ),
                ),
            ],
            options={
                "verbose_name": "文档",
                "verbose_name_plural": "文档",
                "db_table": "documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Paragraph",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="标题"
                    ),
                ),
                ("content", models.TextField(verbose_name="内容")),
                ("char_length", models.IntegerField(default=0, verbose_name="字符数")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "处理失败"),
                            ("embedding", "向量化中"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                (
                    "embedding_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="向量ID"
                    ),
                ),
                ("hit_count", models.IntegerField(default=0, verbose_name="命中次数")),
                (
                    "last_hit_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后命中时间"),
                ),
                ("position", models.IntegerField(default=0, verbose_name="在文档中的位置")),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paragraphs",
                        to="document.document",
                        verbose_name="文档",
                    ),
                ),
                (
                    "knowledge_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paragraphs",
                        to="knowledge_base.knowledgebase",
                        verbose_name="知识库",
                    ),
                ),
            ],
            options={
                "verbose_name": "段落",
                "verbose_name_plural": "段落",
                "db_table": "paragraphs",
                "ordering": ["document", "position"],
            },
        ),
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("content", models.TextField(verbose_name="问题内容")),
                ("hit_count", models.IntegerField(default=0, verbose_name="命中次数")),
                (
                    "last_hit_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后命中时间"),
                ),
                (
                    "knowledge_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problems",
                        to="knowledge_base.knowledgebase",
                        verbose_name="知识库",
                    ),
                ),
            ],
            options={
                "verbose_name": "问题",
                "verbose_name_plural": "问题",
                "db_table": "problems",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentProcessingTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("task_type", models.CharField(max_length=50, verbose_name="任务类型")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "活跃"),
                            ("inactive", "非活跃"),
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="任务状态",
                    ),
                ),
                ("progress", models.IntegerField(default=0, verbose_name="进度百分比")),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                ("result", models.JSONField(default=dict, verbose_name="处理结果")),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_tasks",
                        to="document.document",
                        verbose_name="文档",
                    ),
                ),
            ],
            options={
                "verbose_name": "文档处理任务",
                "verbose_name_plural": "文档处理任务",
                "db_table": "document_processing_tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProblemParagraphMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="document.document",
                        verbose_name="文档",
                    ),
                ),
                (
                    "knowledge_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="knowledge_base.knowledgebase",
                        verbose_name="知识库",
                    ),
                ),
                (
                    "paragraph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="document.paragraph",
                        verbose_name="段落",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="document.problem",
                        verbose_name="问题",
                    ),
                ),
            ],
            options={
                "verbose_name": "问题段落映射",
                "verbose_name_plural": "问题段落映射",
                "db_table": "problem_paragraph_mappings",
                "unique_together": {("problem", "paragraph")},
            },
        ),
    ]
