# Generated by Django 4.2.15 on 2026-06-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="type",
            field=models.CharField(
                choices=[
                    ("base", "通用类型"),
                    ("web", "Web站点"),
                    ("qa", "问答对"),
                    ("chat_archive", "对话归档"),
                    ("table", "表格"),
                    ("markdown", "Markdown"),
                    ("text", "纯文本"),
                ],
                default="base",
                max_length=20,
                verbose_name="文档类型",
            ),
        ),
    ]
