# Generated by Django 4.2.15 on 2026-06-29 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("knowledge_base", "0002_alter_knowledgebaseshare_permission"),
    ]

    operations = [
        migrations.CreateModel(
            name="MCPProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=120)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                (
                    "permission_scope",
                    models.CharField(
                        choices=[
                            ("search_only", "Search only"),
                            ("citations_only", "Search with citations"),
                            ("read_only", "Read-only tools"),
                        ],
                        default="read_only",
                        max_length=40,
                    ),
                ),
                ("allowed_tools", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("rate_limit_per_minute", models.PositiveIntegerField(default=60)),
                ("max_top_k", models.PositiveIntegerField(default=5)),
                ("include_source_content", models.BooleanField(default=True)),
                ("include_metadata", models.BooleanField(default=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcp_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "knowledge_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcp_profiles",
                        to="knowledge_base.knowledgebase",
                    ),
                ),
            ],
            options={
                "db_table": "mcp_profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MCPAccessLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("method", models.CharField(blank=True, default="", max_length=100)),
                ("tool_name", models.CharField(blank=True, default="", max_length=100)),
                ("query", models.TextField(blank=True, default="")),
                ("caller_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("status", models.CharField(default="ok", max_length=20)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("result_count", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="mcp_server.mcpprofile",
                    ),
                ),
            ],
            options={
                "db_table": "mcp_access_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
